### ISSUE TITLE
Change ui-validation package API

### ISSUE THREAD

**Issue by yzhbankov** [zorko-io/zorko-platform#39]
**Problem:**

The package "ui-validation" for invalid parameters throws an error 'ValidationError'. In this case. The client-side of the web application requires some additional logic for error catching in the validation place. This leads to an increase of error handling functionality or require adding a special utility adapter.

**Solution:**

ui-validator not throw an error and return just a false in case the validation is not pass

**Technical Solution:**

change `util-validation` package API.

 - `validate` method should return false in case of validation not pass
 -  returns the validated parameters in other cases.
 -  add `getErrors` method that will return validation error if validation is not pass

**Acceptance:**
 - [x] update unit tests and add new ones
 - [x] update jsdocs
 - [x] update all usages of validator

**Comment by nesterone** [comment]
I don't want to add `getErrors` to the `Validator` interface because it makes instance mutable

I propose the next API:


```
const {result, error} = validator.validate(params)

// or

const [result, error] = validator.validate(params)
```

so in case you no need errors it's just 

const [result] = validator.validate(params)


Also, error is an instance of `ValidationError` from `util-error` and contains a list of errors

**Comment by yzhbankov** [comment]
LGFM
