### ISSUE TITLE
Prepare Examples page for placing reusable components 

### ISSUE THREAD

**Issue by nesterone** [zorko-io/zorko-platform#65]
depends on #56, #64

**Comment by nesterone** [comment]
move App -> features/examples/ExpamplesPage.jsx

switch router

move example components to features/examples/components

**Comment by nesterone** [comment]
![Uploading Documentation - Tailwind CSS 2020-12-10 10-47-34.png…]()

**Comment by whiteadam2** [comment]
1. Please pull my branch and check whether I truly understand structure you wanna implement or not?
2. Plz make description of each folder at least in web-portal-client. Because i have some mess with understanding structure of project
3. Attached Link wont work https://github.com/zorko-io/zorko-platform/issues/65#issuecomment-742376374

**Comment by nesterone** [comment]
Having folders structure here : 

* https://github.com/zorko-io/zorko-platform/tree/dev/apps/web-portal-client#project-structure
* about 'concepts' read here https://github.com/zorko-io/zorko-platform/tree/dev/apps/web-portal-client#design-decisions

regarding checking your structure, plz create PR with `WIP` in title

**Comment by nesterone** [comment]
![Documentation - Tailwind CSS 2020-12-10 10-47-34](https://user-images.githubusercontent.com/75000/102018233-c83eed80-3d74-11eb-8239-bdc3bdb639b2.png)

**Comment by nesterone** [comment]
regarding examples of structure

let's do something like

```
-features/
  -examples/
       components/
               - ValidatorExample.jsx
               - ApiExample.jsx
               - ExamplePage.jsx  
               - ButtonExample.jsx   // for adding buttons use cases
```
